version: '3'

# vars:
#   DISTRO:
#     sh: cat /etc/os-release

dotenv: ['/etc/os-release']

includes:
  k3d:
    optional: true
    taskfile: ~/k3d/Taskfile.k3d.yaml

  opensuse-tumbleweed:
    aliases: ['ot']
    optional: true
    taskfile: ~/Taskfile.opensuse-tumbleweed.yaml

tasks:
  default:
    cmds:
      - task --list

  create-symlinks:
    desc: Create symlinks for dotfiles with automatic backup of existing files
    aliases:
      - cs
    vars:
      # This is needed because this taskfile is symlinked to ~
      REALPATH:
        sh: dirname $(realpath ./Taskfile.yaml)
      FILES:
        sh: >-
          cd $(dirname $(realpath ./Taskfile.yaml)); find . \(
          -name ".gitignore"
          -o -name "bootstrap.sh"
          -o -path "./.git"
          -o -path "./.task"
          -o -path "./darwin"
          -o -path "./linux"
          \) -prune -o \( -type f -o -type l \) -print
    dir: '{{ .REALPATH }}'
    cmds:
      - for:
          var: FILES
        vars:
          SOURCE: '{{ joinPath .REALPATH .ITEM }}'
          DESTINATION: '{{ joinPath .HOME .ITEM }}'
        task: create-symlink
      - task: create-symlinks-darwin
      - task: create-symlinks-linux

  create-symlinks-darwin:
    aliases: [csd]
    platforms: [darwin]
    vars:
      REALPATH:
        sh: echo -n $(dirname $(realpath ./Taskfile.yaml))/darwin
      FILES:
        sh: >-
          cd $(dirname $(realpath ./Taskfile.yaml))/darwin; find . -type f -o -type f -print
    dir: '{{ .REALPATH }}'
    cmds:
      - for:
          var: FILES
        vars:
          SOURCE: '{{ joinPath .REALPATH .ITEM }}'
          DESTINATION: '{{ joinPath .HOME .ITEM }}'
        task: create-symlink

  create-symlinks-linux:
    aliases: [csl]
    platforms: [linux]
    vars:
      REALPATH:
        sh: echo -n "$(dirname $(realpath ./Taskfile.yaml))/linux"
      FILES:
        sh: >-
          cd $(dirname $(realpath ./Taskfile.yaml))/linux; find . -type f -print
    dir: '{{ .REALPATH }}'
    cmds:
      - for:
          var: FILES
        vars:
          SOURCE: '{{ joinPath .REALPATH .ITEM }}'
          DESTINATION: '{{ joinPath .HOME .ITEM }}'
        task: create-symlink

  clean-symlinks:
    desc: Find and delete broken symlinks from $HOME
    aliases: [clean]
    cmds:
      - find {{ .HOME }} -type l ! -exec test -e {} \; -print -delete

  # Package Management

  update:
    desc: Update everything
    aliases: [u]
    cmds:
      - task: brew
      - task: helix
      - cmd: ya pkg add yazi-rs/flavors:catppuccin-macchiato
        ignore_error: true
      - task: "{{ .ID }}:update"

  brew:
    desc: Upgrade homebrew, all packages, and install missing
    aliases: [b]
    cmds:
      - brew update
      - brew upgrade
      - brew bundle
      - brew cleanup

  helix:
    desc: Install and update packages for a helix fork that enable plugins via steel/scheme
    aliases: [h]
    cmds:
      - cargo install --git https://github.com/mattwparas/steel.git steel-forge
      - forge pkg install --git https://github.com/mattwparas/helix-config.git
      - mkdir -p ~/git
      - task: helix-clone
      - task: helix-build
    ignore_error: true

  helix-clone:
    internal: true
    status:
      - test -d ~/git/helix
    dir: ~/git
    cmds:
      - git clone https://github.com/mattwparas/helix.git

  helix-build:
    internal: true
    dir: ~/git/helix
    cmds:
      - git switch steel-event-system
      - git pull
      - cargo xtask steel
    ignore_error: true

  # Internals

  create-symlink:
    internal: true
    requires:
      vars:
        - SOURCE
        - DESTINATION
    cmds:
      - mkdir -p {{ dir .DESTINATION }}
      - ln -fs {{ .SOURCE }} {{ .DESTINATION }}
