version: '3'

includes:
  local:
    taskfile: ~/Taskfile.local.yaml
    optional: true

tasks:
  default:
    cmds:
      - task --list

  create-symlinks:
    desc: Create symlinks for dotfiles with automatic backup of existing files
    aliases:
      - cs
    vars:
      # This is needed because this taskfile is symlinked to ~
      REALPATH:
        sh: dirname $(realpath ./Taskfile.yaml)
    dir: '{{ .REALPATH }}'
    sources:
      - ./**/*
      - exclude: .git/**/*
      - exclude: .gitignore
      - exclude: .task/**/*
      - exclude: bootstrap.sh
      - exclude: darwin/**/*
    cmds:
      - for: sources
        vars:
          SOURCE: '{{ joinPath .REALPATH .ITEM }}'
          DESTINATION: '{{ joinPath .HOME .ITEM }}'
        task: create-symlink
      - task: create-symlinks-darwin

  create-symlinks-darwin:
    aliases: [csd]
    platforms: [darwin]
    vars:
      REALPATH:
        sh: echo -n "$(dirname $(realpath ./Taskfile.yaml))/darwin"
    dir: '{{ .REALPATH }}'
    sources:
      - ./**/*
    cmds:
      - for: sources
        vars:
          SOURCE: '{{ joinPath .REALPATH .ITEM }}'
          DESTINATION: '{{ joinPath .HOME .ITEM }}'
        task: create-symlink

  clean-symlinks:
    desc: Find and delete broken symlinks from $HOME
    aliases: [clean]
    cmds:
      - find {{ .HOME }} -type l ! -exec test -e {} \; -print -delete

  # Package Management

  update:
    desc: Update everything
    aliases: [u]
    cmds:
      - task: brew
      - task: cargo
      - ya pack -a yazi-rs/flavors:catppuccin-macchiato

  brew:
    desc: Upgrade homebrew, all packages, and install missing
    aliases: [b]
    cmds:
      - brew update
      - brew upgrade
      - brew bundle
      - brew cleanup

  cargo:
    desc: Install and update rust packages install via cargo
    aliases: [c]
    cmds:
      - source cargo.sh

  # Ollama

  ollama-build:
    desc: Builds my personal ai model to run with ollama
    aliases: [ob]
    cmds:
      - ollama create personal -f ~/.ollama/personal.Modelfile

  # Internals

  create-symlink:
    internal: true
    requires:
      vars:
        - SOURCE
        - DESTINATION
    cmds:
      - mkdir -p {{ dir .DESTINATION }}
      - ln -fs {{ .SOURCE }} {{ .DESTINATION }}
