version: '3'

includes:
  local:
    taskfile: ~/Taskfile.local
    optional: true

tasks:
  default:
    cmds:
      - task --list

  create-symlinks:
    desc: Create symlinks for dotfiles with automatic backup of existing files
    aliases:
      - cs
    vars:
      REALPATH:
        sh: dirname $(realpath ./Taskfile.yaml)
    dir: '{{ .REALPATH }}'
    sources:
      - ./**/*
      - exclude: .git/**/*
      - exclude: .gitignore
      - exclude: bootstrap.sh
    cmds:
      - for: sources
        cmd: mkdir -p "{{ dir (joinPath .HOME .ITEM) }}"; ln -fs "{{ joinPath .REALPATH .ITEM }}" "{{ joinPath .HOME .ITEM }}"

  upgrade:
    desc: Upgrade homebrew and all installed packages
    aliases:
      - up
    cmds:
      - brew update
      - brew upgrade
      - brew cleanup
