version: '3'

includes:
  local:
    taskfile: ~/Taskfile.local
    optional: true

tasks:
  default:
    cmds:
      - task --list

  create-symlinks:
    desc: Create symlinks for dotfiles with automatic backup of existing files
    aliases:
      - cs
    vars:
      REALPATH:
        sh: dirname $(realpath ./Taskfile.yaml)
    dir: '{{ .REALPATH }}'
    sources:
      - ./**/*
      - exclude: .git/**/*
      - exclude: .gitignore
      - exclude: bootstrap.sh
    cmds:
      - for: sources
        # cmd: echo "{{ .ITEM }}"
        cmd: mkdir -p "{{ dir (joinPath .HOME .ITEM) }}"; ln -fs "{{ joinPath .REALPATH .ITEM }}" "{{ joinPath .HOME .ITEM }}"

  test:
    vars:
      REALPATH:
        sh: dirname $(realpath ./Taskfile.yaml)
    dir: '{{ .REALPATH }}'
    cmds:
      - pwd
      - realpath ./Taskfile.yaml
      - ls -la .
