brew "zellij"
brew "helix"

cask "rancher"
brew "kustomize"
brew "k3d"
brew "k9s"
brew "tilt"

brew "go"

brew "yaml-language-server"
brew "yamlfmt"

brew "lazygit"

cask "slack"

brew "pre-commit"
brew "go-task"
